### ISSUE TITLE
foutje in instructies stimuli.js

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-spr-mw#11]
in stimuli.js staat

// Use FALSE_BUTTON_TEXT if the answer is true,
                                                                  // TRUE_BUTTON_TEXT otherwise

ik neem aan dat true false moet zijn. (ik lees wat vage opmerkingen van studenten nu waar ik uit opmaak dat ze de instructies gevolgd hadden hoewel ze het raar vonden, en uiteindelijk alles hebben zitten omcoderen in de analyse... weet niet of ik dit schattig moet vinden of gewoon niet zo handig van ze - allebei?)

**Comment by maartenuni** [comment]
Het klinkt inderdaad wel of die instructies verbeterd kunnen worden.

Het voelt wel een beetje als bestraft worden voor (te) braaf gedrag.

Ik zal het binnenkort aanpassen.

**Comment by maartenuni** [comment]
De hele file moet nog een keer doorlopen worden op taalfoutjes in de comments. Ik zie wel meer gekke dingen staan.
