### ISSUE TITLE
meertaligen kunnen talen niet invullen

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-spr-mw#13]
Het veld native_language in survey.js staat alleen letters toe, maar tweetaligen moeten ook een spatie, komma, slash etc kunnen gebruiken om meerdere talen in te vullen ('English and Dutch' of
'English/Dutch' etc).

Zou opgelost moeten zijn door
pattern="[a-zA-Z]+" placeholder="Dutch" required>

te vervangen door

pattern="\p{L}+{1,314}$" placeholder="Dutch" required>

**Comment by irisopgithub** [comment]
geldt ook voor all lexical-decision-templates

**Comment by maartenuni** [comment]
Begrijp ik jouw reguliere expressie goed als ik denk, dat je minimaal 1 word wil zien dat bestaat uit allerlei Unicode karakters en maximaal 314 woorden, met eventueel een of meerdere white spaces tussen de woorden?

**Comment by irisopgithub** [comment]
dit is de regex die ik terugkreeg (van jacco) toen ik vorig jaar het probleem meldde dat mensen niet meerdere moedertalen konden invullen. wmb hoeft er helemaal geen restrictie op, behalve dat ze wel iets moeten invullen. slashes, ampersands en spaties moeten toegestaan worden want dat is wat mensen gebruiken om meerdere talen in te vullen. verder zal het me eerlijk gezegd een zorg zijn!

**Comment by maartenuni** [comment]
Ik ga er een andere van maken:
```javascript
/^\s*\p{Letter}+([ ,&/\\]+\p{Letter}+)*\s*$/gu
```

uitleg:
-  **^** match het begin van de input
- **\s*** match 0 of meer whitespaces aan het begin van de input (reken het niet fout als pp per ongeluk begint met een spatie)
- **\p{Letter}+** match een sequentie van allerlei letters  ook letters buiten [a-z] en [A-Z] chinees etc.
- (**[ ,&/\\]+\p{Letter}+)** match 0 of meer scheidings tekens ,/\& etc gevolgd door nog een taal en je kan hier in principe oneindig veel talen invullen
- **\s*** match white space aan het einde
- **$** het einde van de input

**Comment by maartenuni** [comment]
Hmm, jammer alleen dat html input types patterns geen Unicode accepteren, ik verander \p{Letter} in [a-zA-Z], maar dan kunnen de deelnemers geen chinese tekens etc.  invullen..

**Comment by maartenuni** [comment]
Zoals net besproken in de lab meeting, het is de bedoeling dat we de pattern weglaten en dat we de html-input **required** gebruiken, die stond er al, dus het pattern mag weg.
