### ISSUE TITLE
Q voor de condities van de vragen?

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-spr-mw#15]
Zou het mogelijk zijn om de condities van de vragen te coderen met Q ervoor? De vragen hebben nu dezelfde conditie als het item waar ze bijhoren, dus item_type PASSIVE, PRAC etc.
Het zou handig zijn als vragen onderscheidbaar zijn maar de conditie waar ze bijhoren wel nog zichtbaar is, dus als ze bijv. item_type QPASSIVE, QPRAC etc zouden hebben.

Als dat niet (makkelijk) kan, is het uiteraard ook mogelijk om dit in de analyse op te lossen.

**Comment by maartenuni** [comment]
Geen probleem, Als er een nieuwe vraag wordt aangemaakt prepend ik een "Q" voor het item_type.

**Comment by maartenuni** [comment]
added in fee093330dbbe888bd0bfaeadcca4734657ed552
