### ISSUE TITLE
cijfers achter de komma in de reactietijden

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-spr-mw#17]
is het mogelijk om de reactietijden af te ronden op hele milliseconden?

ik weet niet heel precies waar het door komt, maar bij sommige proefpersonen staan er cijfers achter de komma bij de rt's, en bij sommige ppn niet. ik geloof dat de studenten zeiden dat het vooral macgebruikers zijn waarbij je rt's krijgt met soms bizar veel cijfers achter de komma.

ook dit is weer iets waar excel in stikt, ook al zou dat natuurlijk niet moeten. we hebben iig niks aan al die cijfers achter de komma, dus als die gewoon weggerond zouden kunnen worden zou dat het makkelijkst zijn. (maakt de bestanden ook een stuk overzichtelijker).

**Comment by maartenuni** [comment]
Ik kan hier vast iets voor toevoegen. Geen idee waar die verschillen vandaan komen. Ik doe wel een int(round(rt)) of iets dergelijks, zodat je altijd de dichtsbijzijnde hele reactietijd krijgt.

**Comment by maartenuni** [comment]
Ik zal proberen alles waar een RT aan vast zit in af te ronden op hele ms, mocht er ooit per ongeluk toch 1 over het hoofd gezien worden please don't shoot me...

**Comment by irisopgithub** [comment]
ik zou wel gek zijn, wat moeten we zonder jou? ;-)
dankjewel!!

**Comment by maartenuni** [comment]
Ik ziet het ook bij google chrome op linux:
```json
	{
		"rt1": 207.79999995231628,
		"rt2": 231.09999990463257,
		"rt3": 235,
		"rt4": 263.5,
		"rt5": 255.80000019073486,
		"rt6": 231.29999995231628,
		"rt7": 247.60000014305115,
		"rt8": 231.89999985694885,
		"rt9": 247.5,
		"rt10": 239.29999995231628,
		"rt11": 186.89999985694885,
		"rt12": 214.39999985694885,
		"rt13": 225.20000004768372,
		"rt14": 396.59999990463257,
		"rt15": -1,
		"id": 2,
		"item_type": "ACTIVE",
		"uil_save": true,
		"trial_type": "spr-moving-window",
		"trial_index": 15,
		"time_elapsed": 83451,
		"internal_node_id": "0.0-13.0",
		"subject": "hea4g1uk",
		"list": "list1"
	},
```
