### ISSUE TITLE
Engelstalige stimuluslijst

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-spr-mw#2]
Ik heb een Engelstalige stimuluslijst gemaakt, zie bijlage. (txt veranderen naar .js, ik mag geen .js uploaden)

[stimuli.txt](https://github.com/UiL-OTS-labs/jspsych-spr-mw/files/5697786/stimuli.txt)

**Comment by maartenuni** [comment]
Ofcourse i ment stimuli are now in English.
