### ISSUE TITLE
Surveyblokje

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-spr-mw#4]
de laatste drie vragen van de questionnaire zijn gecentreerd terwijl de antwoorden links uitgelijnd zijn, dat maakt het lastig om te zien wat waarbij hoort.

volgens mij is dit gefikst in vislexdec_vp

**Comment by irisopgithub** [comment]
in de output komen de antwoorden in verschillende kolommen, maar alleen in de rij van het surveyblokje.

volgens mij is het in vislexdec_vp zo dat alle antwoorden in maar 1 kolom alleen in die rij komen (was iig wel zo)

aangezien je toch met de hand een proefpersooneigenschappen-tabel moet gaan knutselen als die info niet op elke regel staat, is het beter om het dan maar in 1 kolom te hebben.

dit is uiteraard geen dealbreaker.

**Comment by maartenuni** [comment]
Om deze op te lossen moet ik via CSS overiden dat die vragen niet gecentreerd mogen worden aangeboden. Het is een lelijke oplossing... maar ja, het werkt wel... 
De eerste en tweede pagina van de survey werken via een andere jsPsych plugin, die plugins hebben een ander idee over hoe de surveys zichtbaar moeten zijn.

**Comment by maartenuni** [comment]
Zomenteen los in in ieder geval de formatting van de 2e survey pagina aan.

**Comment by maartenuni** [comment]
De survey alignment is opgelost in 53e0ef8500dc69e7a465dce37297fec9930f50b8
