### ISSUE TITLE
correct_response

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-spr-mw#5]
correct_response in de output kan beter heten: expected_answer.

**Comment by maartenuni** [comment]
fixed in c66d195

**Comment by maartenuni** [comment]
De output voor een vraag is nu:
{
		"rt": 1367,
		"stimulus": "The chauffeur was an old man.",
		"button_pressed": "0",
		"id": 3,
		"expected_answer": "false",
		"uil_save": true,
		"trial_type": "html-button-response",
		"trial_index": 14,
		"time_elapsed": 244270,
		"internal_node_id": "0.0-12.0",
		"subject": "clbu71m9",
		"group": "group1",
		"answer": "false",
		"correct": true
	},
in json, dat zal in aparte kolommen verschijnen in een csv.

**Comment by irisopgithub** [comment]
kan item_type er ook nog bij? als id erbij staat, vast wel.

**Comment by maartenuni** [comment]
Tuurlijk, stom van mij dat ik die over het hoofd heb gezien. Die vond ik waarschijnlijk alleen relevant voor de spr zelf en niet de vraag. Doe ik zo even.

**Comment by irisopgithub** [comment]
vaak is het inderdaad ook niet relevant voor de vraag, dat klopt wel hoor. maar soms wel. tnx!

**Comment by maartenuni** [comment]
Nu ziet het er zo uit:
```
{
	"rt": 1420,
	"stimulus": "The researcher presented old work.",
	"button_pressed": "1",
	"id": 2,
	"item_type": "PRAC",
	"expected_answer": "false",
	"uil_save": true,
	"trial_type": "html-button-response",
	"trial_index": 10,
	"time_elapsed": 35001,
	"internal_node_id": "0.0-8.0",
	"subject": "orpfytxr",
	"group": "group2",
	"answer": "true",
	"correct": false
}
```
Dus het item type zit er ook bij. Dit moet allemaal nog wel even naar de main branch worden gepusht.
