### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-spr-mw#6]
dit is niet echt een issue maar meer een todo/reminder: in de readme ontbreekt nog een lijstje met de outputvariabelen. volgens mij was het plan om ergens een generiek lijstje te maken, en dan per template de specifieke. 

er staan wat spelfoutjes in de readme, mag ik die rechtstreeks editen, of hoe wil je die hebben?

**Comment by maartenuni** [comment]
Je mag wat mij betreft de readme wel editten. Ik moet die dan ook even naar de develop branch mergen maar dat is niet zo'n probleem

**Comment by irisopgithub** [comment]
ok, ik heb 'm geedit, tnx!

**Comment by maartenuni** [comment]
tnxm voor de edits.
